name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: |
        pod install --repo-update --clean-install --project-directory=RosaAlert/
        xcodebuild test -workspace RosaAlert/RosaAlert.xcworkspace -scheme RosaAlert -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=15.4'
